builds:
  - id: "management"
    main: ./cmd/management
    binary: openvpn-auth-oauth2-management-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    no_unique_dist_dir: true
  - id: "user-pass-verify"
    main: ./cmd/management
    binary: openvpn-auth-oauth2-script
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    no_unique_dist_dir: true

